### ISSUE TITLE
Unable to install package on Python 2.7

### ISSUE THREAD

**Issue by jpflouret** [CharlesWillis3/marlin-binary-protocol#2]
I tried to install this package (as a dependency of OctoPrint-MarlinBft) and was unable to do so on Octoprint 1.4.0 running on OctoPi with Python 2.7.16.

    ERROR: Could not find a version that satisfies the requirement marlin-binary-protocol>=0.0.5 (from OctoPrint-MarlinBft==0.1.1) (from versions: none)
    ERROR: No matching distribution found for marlin-binary-protocol>=0.0.5 (from OctoPrint-MarlinBft==0.1.1)

I tried a verbose manually install from the command line and this was the result:

    Non-user install because user site-packages disabled
    Created temporary directory: /tmp/pip-ephem-wheel-cache-4vQW3x
    Created temporary directory: /tmp/pip-req-tracker-ICnBsw
    Initialized build tracking at /tmp/pip-req-tracker-ICnBsw
    Created build tracker: /tmp/pip-req-tracker-ICnBsw
    Entered build tracker: /tmp/pip-req-tracker-ICnBsw
    Created temporary directory: /tmp/pip-install-tTrNTB
    Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
    2 location(s) to search for versions of marlin-binary-protocol:
    * https://pypi.org/simple/marlin-binary-protocol/
    * https://www.piwheels.org/simple/marlin-binary-protocol/
    Fetching project page and analyzing links: https://pypi.org/simple/marlin-binary-protocol/
    Getting page https://pypi.org/simple/marlin-binary-protocol/
    Found index url https://pypi.org/simple
    Looking up "https://pypi.org/simple/marlin-binary-protocol/" in the cache
    Request header has "max_age" as 0, cache bypassed
    Starting new HTTPS connection (1): pypi.org:443
    https://pypi.org:443 "GET /simple/marlin-binary-protocol/ HTTP/1.1" 304 0
      Skipping link: none of the wheel's tags match: py3-none-any: https://files.pythonhosted.org/packages/43/e2/48762de500dff28e28af0d660f17960ff15b24341ddc6b28ffef1acaec70/marlin_binary_protocol-0.0.1-py3-none-any.whl#sha256=a2ecf7e4e20c16eda181f3c5125f1d9c43ed00880ad07120696eca60f8d9b36f (from https://pypi.org/simple/marlin-binary-protocol/) (requires-python:>=2.7,>=3.7)
      Skipping link: none of the wheel's tags match: py3-none-any: https://files.pythonhosted.org/packages/43/91/1be021c71ddcc6ad05ad912b28041883fdf4b99a75eb3d0b59e3907c7dee/marlin_binary_protocol-0.0.2-py3-none-any.whl#sha256=1c023ac0ed1614ae393e59b2646333e987131dc503328cae8f3380eb93f7d784 (from https://pypi.org/simple/marlin-binary-protocol/) (requires-python:>=2.7,>=3.7)
      Link requires a different Python (2.7.16 not in: u'>=2.7,>=3.7'): https://files.pythonhosted.org/packages/7f/e9/659d857f6627993c98364c2f7236d67bc50fdbf3a033cfd53a1d30e9687a/marlin_binary_protocol-0.0.2.tar.gz#sha256=ded8e23b25cb3f1ee744e2163692c5603ed3f9fa578b9fb7e0657026b8ec671f (from https://pypi.org/simple/marlin-binary-protocol/) (requires-python:>=2.7,>=3.7)
      Skipping link: none of the wheel's tags match: py3-none-any: https://files.pythonhosted.org/packages/a4/92/88a8fe802a8a65158b8a48026ed23be57324f1727a5ba152c908ee7f1edc/marlin_binary_protocol-0.0.3-py3-none-any.whl#sha256=9e85e58d3cd2e8ebb572663968b11b4172a0c4a99db4f0a87095167596352387 (from https://pypi.org/simple/marlin-binary-protocol/) (requires-python:>=2.7,>=3.7)
      Link requires a different Python (2.7.16 not in: u'>=2.7,>=3.7'): https://files.pythonhosted.org/packages/be/56/4e95d071244dad5b909a7c0cf76feaf33b32cb129f522d93e8f354e8c93e/marlin_binary_protocol-0.0.3.tar.gz#sha256=f0c2807d0ec95d2f24d6f6ddf3a046492e0df2a6e363483abe4bc43a44bd91cd (from https://pypi.org/simple/marlin-binary-protocol/) (requires-python:>=2.7,>=3.7)
      Skipping link: none of the wheel's tags match: py3-none-any: https://files.pythonhosted.org/packages/cb/b9/b2a300409c4da95ce1b0be5c1e5df75b5bac4d8f4923fffac63362421add/marlin_binary_protocol-0.0.4-py3-none-any.whl#sha256=461dd961797a31ef3ae186b89ead4afc489c5d3170dcdb79cd6ddb6affbd0387 (from https://pypi.org/simple/marlin-binary-protocol/) (requires-python:>=2.7,>=3.7)
      Link requires a different Python (2.7.16 not in: u'>=2.7,>=3.7'): https://files.pythonhosted.org/packages/79/35/b9498e25d28f85658e654892362d201c3b5dae1f1b15a06eec2c9b27cbf5/marlin_binary_protocol-0.0.4.tar.gz#sha256=982f791142b64c59b642630030dddfa75fb9e0fc54eb996685749b67ff5ba728 (from https://pypi.org/simple/marlin-binary-protocol/) (requires-python:>=2.7,>=3.7)
      Skipping link: none of the wheel's tags match: py3-none-any: https://files.pythonhosted.org/packages/fe/22/1c64cbdc8cf8a2ed7703dfe837ad6c849ad141a0b122a75dad9edd1484b1/marlin_binary_protocol-0.0.5-py3-none-any.whl#sha256=bec80262ec8c8515e1817147ebad306f1d44a433493ed3ab71960036d9c2d34e (from https://pypi.org/simple/marlin-binary-protocol/) (requires-python:>=2.7,>=3.7)
      Link requires a different Python (2.7.16 not in: u'>=2.7,>=3.7'): https://files.pythonhosted.org/packages/76/73/f24c4fa543d59163ade4d9a4df2496ef166728dae07125a64101bb198f2f/marlin_binary_protocol-0.0.5.tar.gz#sha256=b6a75f95e55f87d4518cdb58936be2a0c6a6942700baa0b50def8a44d0313fe9 (from https://pypi.org/simple/marlin-binary-protocol/) (requires-python:>=2.7,>=3.7)
    Fetching project page and analyzing links: https://www.piwheels.org/simple/marlin-binary-protocol/
    Getting page https://www.piwheels.org/simple/marlin-binary-protocol/
    Found index url https://www.piwheels.org/simple
    Looking up "https://www.piwheels.org/simple/marlin-binary-protocol/" in the cache
    Request header has "max_age" as 0, cache bypassed
    Starting new HTTPS connection (1): www.piwheels.org:443
    https://www.piwheels.org:443 "GET /simple/marlin-binary-protocol/ HTTP/1.1" 200 323
    Updating cache with response from "https://www.piwheels.org/simple/marlin-binary-protocol/"
    Caching due to etag
      Skipping link: none of the wheel's tags match: py3-none-any: https://www.piwheels.org/simple/marlin-binary-protocol/marlin_binary_protocol-0.0.4-py3-none-any.whl#sha256=86b915bcfbd1c8b36d73345ab1e3ed53b203b6d8abadfc5bf685faa683a79cf0 (from https://www.piwheels.org/simple/marlin-binary-protocol/)
      Skipping link: none of the wheel's tags match: py3-none-any: https://www.piwheels.org/simple/marlin-binary-protocol/marlin_binary_protocol-0.0.3-py3-none-any.whl#sha256=65959d35afb0d120778dc9ff13eb8718321ecb7474f3de55e155aa5b479682c5 (from https://www.piwheels.org/simple/marlin-binary-protocol/)
      Skipping link: none of the wheel's tags match: py3-none-any: https://www.piwheels.org/simple/marlin-binary-protocol/marlin_binary_protocol-0.0.2-py3-none-any.whl#sha256=ee8b304d7d73cf695c5d38b088ebd45e3d0562d296e4589b15477632cb95c69e (from https://www.piwheels.org/simple/marlin-binary-protocol/)
    Given no hashes to check 0 links for project 'marlin-binary-protocol': discarding no candidates
    ERROR: Could not find a version that satisfies the requirement marlin-binary-protocol (from versions: none)
    ERROR: No matching distribution found for marlin-binary-protocol
    Exception information:
    Traceback (most recent call last):
      File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
        status = self.run(options, args)
      File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
        return func(self, options, args)
      File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 333, in run
        reqs, check_supported_wheels=not options.target_dir
      File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 179, in resolve
        discovered_reqs.extend(self._resolve_one(requirement_set, req))
      File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
        abstract_dist = self._get_abstract_dist_for(req_to_install)
      File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 313, in _get_abstract_dist_for
        self._populate_link(req)
      File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 279, in _populate_link
        req.link = self.finder.find_requirement(req, upgrade)
      File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_internal/index/package_finder.py", line 930, in find_requirement
        req)
    DistributionNotFound: No matching distribution found for marlin-binary-protocol
    Removed build tracker: '/tmp/pip-req-tracker-ICnBsw'

**Link requires a different Python (2.7.16 not in: u'>=2.7,>=3.7')**

I think the version specifier `>=2.7,>=3.7` means gretar than 2.7 **and** greter than 3.5? https://www.python.org/dev/peps/pep-0440/#version-specifiers

**Comment by trippwill** [comment]
@jpflouret , right you are! Updated the specifier and pushed v0.0.6 to pypi from this commit https://github.com/CharlesWillis3/marlin-binary-protocol/commit/e3823c30901c57ba4cfce52bcf65735efceab5dd

I've also yanked v0.0.5 from pypi. I've successfully pip installed on both python 2.7 and python 3.7.
